In [47]:
#Уплотнить заданную матрицу, удаляя из нее строки и столбцы, заполненные нулями. Найти
#номер первой из строк, содержащих хотя бы один положительный элемент.

import numpy as np
def creat():
    mat = []
    print('Вводите матрицу, завершив ввод словам end')
    while True:
        s = input()
        if s == "end":
            break
        row = [int(x) for x in s.split()]
        mat.append(row)
    mat = np.array(mat)
    return(mat)
 
def plot(mat):
    mat = mat[~np.all(mat == 0, axis=1)]
    return mat
 
def numder(mat):
    num =''
    for i in range(len(mat)):
        for j in range(len(mat.T)):
            if mat[i][j] > 0:
                num += str(i)
                break
    return num[0]
 
mat = creat()
print('Матрица до изменения:\n{}'.format(mat))
m = [0]*len(mat)
m1 = [0]*len(mat.T)
k = 2
for i in range(len(mat)):
    if np.all(mat[i]==0):
        k = 1
        break
if k == 1: mat = plot(mat)  
for i in range(len(mat.T)):
    if np.all(mat.T[i]==0):
        k = 0
        break
if k == 0: mat = plot(mat.T)  
print('Матрица после изменения:\n{}'.format(mat))
print('Номер первой из строк: {}'.format(int(numder(mat))+1))

Вводите матрицу, завершив ввод словам end
-2 -3 -10 -1 0
0 0 0 0 0
-4 3 -1 1 5
0 0 0 0 0
1 1 2 3 4
end
Матрица до изменения:
[[ -2  -3 -10  -1   0]
 [  0   0   0   0   0]
 [ -4   3  -1   1   5]
 [  0   0   0   0   0]
 [  1   1   2   3   4]]
Матрица после изменения:
[[ -2  -3 -10  -1   0]
 [ -4   3  -1   1   5]
 [  1   1   2   3   4]]
Номер первой из строк: 2
